/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dxUbaa3QWlJ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { CardContent, Card } from "@/components/ui/card";
import Link from "next/link";

export function Dashboard() {
  return (
    <main className="flex flex-col gap-8 p-6 md:p-10">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold">Classrooms</h1>
        <Link href="/joinClassroom">
          <Button>
            <PlusIcon className="mr-2 h-4 w-4" />
            Join new Class
          </Button>
        </Link>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <Card>
          <CardContent className="flex flex-col items-center justify-center p-6 gap-4">
            <ClapperboardIcon className="h-12 w-12 text-gray-500 dark:text-gray-400" />
            <div className="text-lg font-semibold">Chemistry</div>
            <div className="flex gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="h-4 w-4" />
                <span>Dr. John Doe</span>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center justify-center p-6 gap-4">
            <ClapperboardIcon className="h-12 w-12 text-gray-500 dark:text-gray-400" />
            <div className="text-lg font-semibold">DBMS</div>
            <div className="flex gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="h-4 w-4" />
                <span>Dr. John Doe</span>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center justify-center p-6 gap-4">
            <ClapperboardIcon className="h-12 w-12 text-gray-500 dark:text-gray-400" />
            <div className="text-lg font-semibold">DSA</div>
            <div className="flex gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="h-4 w-4" />
                <span>Mr Johnson Lee</span>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center justify-center p-6 gap-4">
            <ClapperboardIcon className="h-12 w-12 text-gray-500 dark:text-gray-400" />
            <div className="text-lg font-semibold">Computer Networks</div>
            <div className="flex gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="h-4 w-4" />
                <span>Dr. John Doe</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}

function ClapperboardIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20.2 6 3 11l-.9-2.4c-.3-1.1.3-2.2 1.3-2.5l13.5-4c1.1-.3 2.2.3 2.5 1.3Z" />
      <path d="m6.2 5.3 3.1 3.9" />
      <path d="m12.4 3.4 3.1 4" />
      <path d="M3 11h18v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z" />
    </svg>
  );
}

function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
